Get the data
------------
Download the file and store it in the `data` folder
```{r, eval=FALSE}
library(data.table)
if(!file.exists("./data")){dir.create("./data")}
url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(url, destfile = "./data/Dataset.zip")
```

Unzip the file
--------------
A new directory (`UCI HAR Dataset`) will be created when the file is unzipped. 
```{r, eval=FALSE}
unzip("./data/Dataset.zip")
```

Read the files
--------------
Subject, Labels and Data files are stored in `train` and `test` folders, respectively. A full
description can be found in the `README.txt` file
```{r, eval=FALSE}
dtSubjectTrain <- fread("./UCI HAR Dataset/train/subject_train.txt")
dtSubjectTest <- fread("./U/UCI HAR Dataset/test/subject_test.txt")
```

```{r, eval=FALSE}
dtActivityTrain <- fread("./UCI HAR Dataset/train/y_train.txt")
dtActivityTest <- fread("./UCI HAR Dataset/train/y_test.txt")
```

```{r, eval=FALSE}
dtTrain <- fread("./UCI HAR Dataset/train/X_train.txt")
dtActivity <- fread("./UCI HAR Dataset/train/X_test.txt")
```

Operations
----------
Todo